# Generated by Django 6.0.5 on 2026-05-25 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SecureMail', '0002_alter_emailmessage_in_trash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='sha256',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='attachment',
            name='vt_report',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
