# Generated by Django 6.0.5 on 2026-05-25 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SecureMail', '0003_attachment_sha256_attachment_vt_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2000)),
                ('threat_type', models.CharField(blank=True, max_length=100, null=True)),
                ('confidence', models.FloatField(default=0.0)),
                ('risk_score', models.FloatField(default=0.0)),
                ('is_malicious', models.BooleanField(default=False)),
                ('gsb_report', models.JSONField(blank=True, null=True)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_analyses', to='SecureMail.emailmessage')),
            ],
            options={
                'verbose_name_plural': 'Link Analyses',
            },
        ),
    ]
