# Generated by Django 6.0.5 on 2026-05-25 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SecureMail', '0004_linkanalysis'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.0)),
                ('category', models.CharField(choices=[('safe', 'Safe'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='safe', max_length=20)),
                ('content_risk', models.FloatField(default=0.0)),
                ('link_risk', models.FloatField(default=0.0)),
                ('attachment_risk', models.FloatField(default=0.0)),
                ('reputation_risk', models.FloatField(default=0.0)),
                ('explanation', models.TextField()),
                ('factors_json', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detailed_risk', to='SecureMail.emailmessage')),
            ],
        ),
    ]
