# Generated by Django 6.0.5 on 2026-05-25 10:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SecureMail', '0006_connectedaccount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmessage',
            name='folder',
            field=models.CharField(db_index=True, default='INBOX', max_length=50),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='gmail_message_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='snippet',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='thread_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='emailmessage',
            unique_together={('user', 'gmail_message_id')},
        ),
    ]
