# Generated by Django 6.0.5 on 2026-05-25 11:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SecureMail', '0007_emailmessage_folder_emailmessage_gmail_message_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailmessage',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
