# Generated by Django 6.0.5 on 2026-05-25 16:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SecureMail', '0009_syncjob_alter_emailmessage_risk_score_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmessage',
            name='analysis_version',
            field=models.CharField(default='1.0.0', max_length=50),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='ml_label',
            field=models.CharField(db_index=True, default='SAFE', max_length=20),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='ml_score',
            field=models.FloatField(db_index=True, default=0.0),
        ),
        migrations.AddIndex(
            model_name='emailmessage',
            index=models.Index(fields=['ml_score'], name='SecureMail__ml_scor_7e11d8_idx'),
        ),
        migrations.AddIndex(
            model_name='emailmessage',
            index=models.Index(fields=['ml_label'], name='SecureMail__ml_labe_5cce12_idx'),
        ),
    ]
