# Generated by Django 6.0.5 on 2026-05-25 17:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SecureMail', '0010_emailmessage_analysis_version_emailmessage_ml_label_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SenderReputationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=255, unique=True)),
                ('frequency', models.IntegerField(default=0)),
                ('historical_safe_count', models.IntegerField(default=0)),
                ('historical_phishing_count', models.IntegerField(default=0)),
                ('reputation_score', models.FloatField(default=50.0)),
            ],
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='analysis_completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='analysis_reasons',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='category',
            field=models.CharField(db_index=True, default='UNKNOWN', max_length=50),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='category_confidence',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='sender_reputation',
            field=models.FloatField(default=50.0),
        ),
        migrations.AddIndex(
            model_name='emailmessage',
            index=models.Index(fields=['category'], name='SecureMail__categor_eb608d_idx'),
        ),
    ]
