# Generated by Django 6.0.5 on 2026-05-25 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SecureMail', '0011_senderreputationmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmessage',
            name='html_body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='plain_body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
