# Generated by Django 6.0.5 on 2026-05-28 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SecureMail', '0012_emailmessage_html_body_emailmessage_plain_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmessage',
            name='is_deleted_on_provider',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
