# Generated by Django 6.0.5 on 2026-05-28 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SecureMail', '0013_emailmessage_is_deleted_on_provider'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailmessage',
            old_name='is_deleted_on_provider',
            new_name='is_remote_deleted',
        ),
    ]
