# Generated by Django 6.0.5 on 2026-07-21 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SecureMail', '0014_rename_is_deleted_on_provider_emailmessage_is_remote_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='alert_digest',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='alert_threats',
            field=models.BooleanField(default=True),
        ),
    ]
