# Generated by Django 6.0.5 on 2026-07-22 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SecureMail', '0015_profile_alert_digest_profile_alert_threats'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmessage',
            name='dkim_pass',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='dmarc_pass',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='spf_pass',
            field=models.BooleanField(default=True),
        ),
    ]
