# Generated by Django 6.0.5 on 2026-07-22 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SecureMail', '0016_emailmessage_dkim_pass_emailmessage_dmarc_pass_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='language',
            field=models.CharField(default='English (US)', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='timezone',
            field=models.CharField(default='UTC (Coordinated Universal Time)', max_length=50),
        ),
    ]
