# Generated by Django 6.0.5 on 2026-07-23 16:42

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SecureMail', '0017_profile_language_profile_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectedaccount',
            name='access_token',
            field=encrypted_model_fields.fields.EncryptedTextField(),
        ),
        migrations.AlterField(
            model_name='connectedaccount',
            name='refresh_token',
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True, null=True),
        ),
    ]
