# Generated by Django 6.0.5 on 2026-07-28 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SecureMail', '0018_alter_connectedaccount_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectedaccount',
            name='history_id',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
