# Generated by Django 6.0.5 on 2026-07-28 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SecureMail', '0019_connectedaccount_history_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ai_analysis',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='alert_weekly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='attachment_scan',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='browser_notifs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='email_notifs',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='risk_threshold',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='rt_analysis',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='safe_browsing',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='url_analysis',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='vt_integration',
            field=models.BooleanField(default=True),
        ),
    ]
