# Generated by Django 6.0.5 on 2026-07-28 15:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SecureMail', '0020_profile_ai_analysis_profile_alert_weekly_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='ai_analysis',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='alert_weekly',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='attachment_scan',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='browser_notifs',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='email_notifs',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='risk_threshold',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='rt_analysis',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='safe_browsing',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='url_analysis',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='vt_integration',
        ),
        migrations.CreateModel(
            name='EmailReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('false_positive', 'False Positive'), ('true_positive', 'True Positive')], db_index=True, max_length=20)),
                ('prediction', models.CharField(max_length=50)),
                ('comment', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='SecureMail.emailmessage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
