# Generated by Django 6.0.7 on 2026-07-30 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SecureMail', '0021_remove_profile_ai_analysis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='md5',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='attachment',
            name='scan_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('QUEUED', 'Queued'), ('ANALYZING', 'Analyzing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='attachment',
            name='upload_timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.CreateModel(
            name='AttachmentAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_score', models.FloatField(default=0.0)),
                ('risk_level', models.CharField(default='UNKNOWN', max_length=50)),
                ('findings', models.JSONField(default=list)),
                ('metadata', models.JSONField(default=dict)),
                ('iocs', models.JSONField(default=list)),
                ('entropy', models.FloatField(default=0.0)),
                ('analyzer_used', models.CharField(max_length=100)),
                ('analysis_version', models.CharField(default='1.0.0', max_length=50)),
                ('execution_time_ms', models.FloatField(default=0.0)),
                ('errors', models.JSONField(default=list)),
                ('raw_report', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('attachment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='SecureMail.attachment')),
            ],
        ),
    ]
